version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  img-arena-coding-challenge:
    build: .
    container_name: img-arena-coding-challenge
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/img_arena_golf
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: supersecurepassword
