spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/img_arena_golf
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view:
      server: false
server:
  error:
    include-message: always