spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/img_arena_golf
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view:
      server: false
  flyway:
    baseline-on-migrate: true
  error:
    include-message: always
